apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts"},"name":"argo-rollouts"},"rules":[{"apiGroups":["argoproj.io"],"resources":["rollouts","rollouts/status","rollouts/finalizers"],"verbs":["get","list","watch","update","patch"]},{"apiGroups":["argoproj.io"],"resources":["analysisruns","analysisruns/finalizers","experiments","experiments/finalizers"],"verbs":["create","get","list","watch","update","patch","delete"]},{"apiGroups":["argoproj.io"],"resources":["analysistemplates","clusteranalysistemplates"],"verbs":["get","list","watch"]},{"apiGroups":["apps"],"resources":["replicasets"],"verbs":["create","get","list","watch","update","patch","delete"]},{"apiGroups":["","apps"],"resources":["deployments","podtemplates"],"verbs":["get","list","watch","update"]},{"apiGroups":[""],"resources":["services"],"verbs":["get","list","watch","patch","create","delete"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create","get","update"]},{"apiGroups":[""],"resources":["secrets","configmaps"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods"],"verbs":["list","update","watch"]},{"apiGroups":[""],"resources":["pods/eviction"],"verbs":["create"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","update","patch"]},{"apiGroups":["networking.k8s.io","extensions"],"resources":["ingresses"],"verbs":["create","get","list","watch","update","patch"]},{"apiGroups":["batch"],"resources":["jobs"],"verbs":["create","get","list","watch","update","patch","delete"]},{"apiGroups":["networking.istio.io"],"resources":["virtualservices","destinationrules"],"verbs":["watch","get","update","patch","list"]},{"apiGroups":["split.smi-spec.io"],"resources":["trafficsplits"],"verbs":["create","watch","get","update","patch"]},{"apiGroups":["getambassador.io","x.getambassador.io"],"resources":["mappings","ambassadormappings"],"verbs":["create","watch","get","update","list","delete"]},{"apiGroups":[""],"resources":["endpoints"],"verbs":["get"]},{"apiGroups":["elbv2.k8s.aws"],"resources":["targetgroupbindings"],"verbs":["list","get"]},{"apiGroups":["appmesh.k8s.aws"],"resources":["virtualservices"],"verbs":["watch","get","list"]},{"apiGroups":["appmesh.k8s.aws"],"resources":["virtualnodes","virtualrouters"],"verbs":["watch","get","list","update","patch"]},{"apiGroups":["traefik.containo.us","traefik.io"],"resources":["traefikservices"],"verbs":["watch","get","update"]},{"apiGroups":["apisix.apache.org"],"resources":["apisixroutes"],"verbs":["watch","get","update"]}]}
  creationTimestamp: "2024-11-25T18:46:39Z"
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts
  resourceVersion: "1785450"
  uid: 1dfc6076-900e-41a3-9345-e734290fab2f
rules:
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  - rollouts/status
  - rollouts/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - analysisruns/finalizers
  - experiments
  - experiments/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - analysistemplates
  - clusteranalysistemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  - apps
  resources:
  - deployments
  - podtemplates
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  verbs:
  - watch
  - get
  - update
  - patch
  - list
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - create
  - watch
  - get
  - update
  - patch
- apiGroups:
  - getambassador.io
  - x.getambassador.io
  resources:
  - mappings
  - ambassadormappings
  verbs:
  - create
  - watch
  - get
  - update
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
- apiGroups:
  - elbv2.k8s.aws
  resources:
  - targetgroupbindings
  verbs:
  - list
  - get
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualservices
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualnodes
  - virtualrouters
  verbs:
  - watch
  - get
  - list
  - update
  - patch
- apiGroups:
  - traefik.containo.us
  - traefik.io
  resources:
  - traefikservices
  verbs:
  - watch
  - get
  - update
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixroutes
  verbs:
  - watch
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - tcproutes
  - udproutes
  - tlsroutes
  - gateway
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - create
