apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-success-rate
  namespace: traffic-router
spec:
  metrics:
  - name: success-rate
    #initialDelay: 10s
    interval: 20s
    count: 5
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090
        query: |
           count(kube_pod_info{namespace="test"})
    successCondition: "result[0] >= 4"
    failureCondition: "result[0] < 4"
    failureLimit: 3









