apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- services.yaml
- gateway.yaml
- httproute.yaml 
- rollout.yaml
- waypoint.yaml
- layer4-AuthorizationPolicy.yaml
- layer7-auth.yaml
namespace: traffic-router
